### ISSUE TITLE
login.php

### ISSUE THREAD

**Issue by rysiekuk** [melbahja/phpsls#1]
I'm getting this error for the line in login.php

line 45   <?= (new form($sls->session))->token('login'); ?>

Parse error: syntax error, unexpected T_OBJECT_OPERATOR, expecting ',' or ';' in /............/account/login.php on line 45

Richard

**Comment by melbahja** [comment]
hello, 
please use php version >= 5.4 
thank you 
mohamed

**Comment by rysiekuk** [comment]
That was sorted with php 5.4 Thank You.
But now I've got ' request or token is not valid ' when try to register or login

Richard

**Comment by melbahja** [comment]
what's the problem  ?

**Comment by faidhim** [comment]
I also get request or token is not valid on trying to login or after submitting to register ! using PHP 5.6

**Comment by melbahja** [comment]
hi @faidhim ,
check the session path or domian ?

**Comment by faidhim** [comment]
Excellent! i shifted the /subdir out of domain name to other and worked fine. Great piece of coding by the way. Thank you

**Comment by melbahja** [comment]
Good luck
